# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160710_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='peopleGroup',
        ),
        migrations.AddField(
            model_name='person',
            name='peopleGroups',
            field=models.ManyToManyField(blank=True, related_name='people', to='blog.PeopleGroup'),
        ),
    ]
