# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160710_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='peopleGroups',
            field=models.ManyToManyField(related_name='people', to='blog.PeopleGroup'),
        ),
    ]
