# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160710_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='peoplegroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='person',
            name='peopleGroups',
            field=models.ManyToManyField(blank=True, null=True, related_name='people', to='blog.PeopleGroup'),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
    ]
