# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20160710_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='PeopleGroup',
            new_name='UserGroup',
        ),
        migrations.RemoveField(
            model_name='person',
            name='peopleGroups',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RenameField(
            model_name='shoplist',
            old_name='peopleGroup',
            new_name='userGroup',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userGroups',
            field=models.ManyToManyField(blank=True, related_name='users', to='blog.UserGroup'),
        ),
    ]
