# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160711_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shopLists',
        ),
        migrations.AddField(
            model_name='item',
            name='shopList',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blog.ShopList'),
            preserve_default=False,
        ),
    ]
